# Generated by Django 3.2.4 on 2021-07-10 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('misc', '0003_alter_abstract_post_model_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogTagModel',
            fields=[
                ('abstract_tag_model_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='misc.abstract_tag_model')),
            ],
            bases=('misc.abstract_tag_model',),
        ),
        migrations.CreateModel(
            name='BlogPostModel',
            fields=[
                ('abstract_post_model_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='misc.abstract_post_model')),
                ('tags', models.ManyToManyField(to='blog.BlogTagModel')),
            ],
            options={
                'verbose_name_plural': 'Posty',
            },
            bases=('misc.abstract_post_model',),
        ),
    ]
