# Generated by Django 3.2.4 on 2021-06-28 15:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostmodel',
            name='text',
            field=models.TextField(default='default', max_length=255),
        ),
        migrations.AlterField(
            model_name='blogpostmodel',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='blogpostmodel',
            name='title',
            field=models.CharField(default='default', max_length=255),
        ),
    ]
