# Generated by Django 3.2.4 on 2021-07-10 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mediaApp', '0003_alter_imagemodel_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='abstract_content_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateEdited', models.DateTimeField(auto_now=True, null=True)),
                ('dateCreated', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='abstract_place_model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='abstract_tag_model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tag_name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Tagi',
            },
        ),
        migrations.CreateModel(
            name='abstract_post_model',
            fields=[
                ('abstract_content_model_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='misc.abstract_content_model')),
                ('title', models.CharField(default='default', max_length=255)),
                ('text', models.TextField(default='default')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mediaApp.imagemodel')),
            ],
            bases=('misc.abstract_content_model',),
        ),
    ]
