# Generated by Django 3.2.4 on 2021-07-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstract_content_model',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
