# Generated by Django 3.2.4 on 2021-07-10 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mediaApp', '0003_alter_imagemodel_options'),
        ('misc', '0002_alter_abstract_content_model_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstract_post_model',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mediaApp.imagemodel'),
        ),
    ]
