# Generated by Django 3.2.4 on 2021-07-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0003_alter_abstract_post_model_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abstract_tag_model',
            options={},
        ),
        migrations.AddField(
            model_name='abstract_place_model',
            name='placeName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
