# Generated by Django 3.2.4 on 2021-06-23 20:48

from django.db import migrations, models
import news.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.PositiveIntegerField(default=news.models.sequence_id, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
            ],
        ),
    ]
