# Generated by Django 3.2.4 on 2021-06-24 15:48

from django.db import migrations, models
import news.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='text',
            field=models.TextField(default='default'),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='id',
            field=models.PositiveIntegerField(default=news.models.test_model_sequence_id, primary_key=True, serialize=False, unique=True),
        ),
    ]
