# Generated by Django 3.2.4 on 2021-06-24 17:44

from django.db import migrations, models
import django.db.models.deletion
import news.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20210624_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagModel',
            fields=[
                ('id', models.PositiveIntegerField(default=news.models.tagmodel_sequence_id, primary_key=True, serialize=False, unique=True)),
                ('tag_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='testmodel',
            name='tags',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='news.tagmodel'),
        ),
    ]
