# Generated by Django 3.2.4 on 2021-06-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20210624_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagListModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_list', models.ManyToManyField(to='news.TagModel')),
            ],
        ),
    ]
