# Generated by Django 3.2.4 on 2021-06-24 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20210624_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testmodel',
            name='tags',
        ),
        migrations.AddField(
            model_name='testmodel',
            name='tags',
            field=models.ManyToManyField(default=None, null=True, to='news.TagModel'),
        ),
        migrations.DeleteModel(
            name='TagListModel',
        ),
    ]
