# Generated by Django 3.2.4 on 2021-06-26 10:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20210624_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 6, 26, 10, 0, 59, 635045, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='text',
            field=models.CharField(default='default', max_length=1024),
        ),
    ]
