# Generated by Django 3.2.4 on 2021-06-26 18:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20210626_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 6, 26, 18, 20, 57, 5428, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='text',
            field=models.TextField(default='default', max_length=1024),
        ),
    ]
