# Generated by Django 3.2.4 on 2021-06-26 18:27

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20210626_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='news.imagemodel'),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 6, 26, 18, 27, 10, 742078, tzinfo=utc)),
        ),
    ]
