# Generated by Django 3.2.4 on 2021-06-28 11:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_auto_20210627_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 28, 11, 23, 18, 128478, tzinfo=utc)),
        ),
    ]
