# Generated by Django 3.2.4 on 2021-06-28 11:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_alter_testmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 28, 11, 31, 27, 270333, tzinfo=utc)),
        ),
    ]
