# Generated by Django 3.2.4 on 2021-06-28 15:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_auto_20210628_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
