# Generated by Django 3.2.4 on 2021-07-01 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mediaApp', '0002_imagemodel_alias'),
        ('news', '0015_alter_testmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mediaApp.imagemodel'),
        ),
        migrations.DeleteModel(
            name='ImageModel',
        ),
    ]
