# Generated by Django 3.2.4 on 2021-07-01 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='alias',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
